version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/redis/config:/opt/config
      - /home/docker/redis/data:/data
    command: redis-server /opt/config/redis.conf
