spring:
  application:
    name: shoes-mall-backend
#  mvc:
#    static-path-pattern: /Files/**
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shoes_mall
#    username: root
#    password: JCPYJH913?...
    url: jdbc:mysql://47.108.52.10:3306/shoes_mall
    username: root
    password: JCPYJH913?...

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 500MB
      max-request-size: 4500MB
  data:
    redis:
      database: 1
      host: 47.108.52.10
      port: 6379
      timeout: 5000
      password: JCPYJH913?...
  mail:
    host: smtp.qq.com
    port: 465
    username: 2773190794@qq.com
    password: pgwkdpzccshmdcce
    test-connection: true
    protocol: smtp # SMTP邮件协议
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  web:
    resources:
      static-locations: file:Files

server:
  address: 0.0.0.0
  port: 2913
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ewan.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# Logger Config
logging:
  level:
    com.hexadecimal: debug

#minio
minio:
  endpoint: http://139.9.181.192:9000
  accessKey: admin
  secretKey: admin123
  buketName: shoes-mall